akvo/akvo-web

code/wp-content/themes/Akvo-responsive/css/main.css

fix https://github.com/akvo/akvo-web/issues/518

[#518] fix misaligned profiles on Team page

---

code/wp-content/themes/Akvo-responsive/css/main.scss

fix [#518](https://github.com/akvo/akvo-web/issues/518)
first PR for #518 incorrectly edited main.css instead of main.scss
This PR correctly fixes main.scss

[#518] (2) fix misaligned profiles on Team page

---

code/wp-content/themes/Akvo-responsive/css/main.css
code/wp-content/themes/Akvo-responsive/css/main.scss
code/wp-content/themes/Akvo-responsive/flowhelpPage.php

Add newsletter signup fields to FLOW help page as per #479

[#479] Add bulletin sign up to FLOW help page

---

code/wp-content/themes/Akvo-responsive/css/main.css
code/wp-content/themes/Akvo-responsive/css/main.scss
code/wp-content/themes/Akvo-responsive/newsletterPage.php

Add newsletter signup page for issue [#479](https://github.com/akvo/akvo-web/issues/479)

[#479] Create newsletter page to view and subscribe all Akvo newsletters

---

code/wp-content/themes/Akvo-responsive/css/main.css
code/wp-content/themes/Akvo-responsive/css/main.scss
code/wp-content/themes/Akvo-responsive/productpage-rsr-whatsnew.php
code/wp-content/themes/Akvo-responsive/productpage-rsr.php

Add "What's new" page as per #394

[#394] Add RSR "what's new" page

---

code/wp-content/themes/Akvo-responsive/css/main.css
code/wp-content/themes/Akvo-responsive/css/main.scss

[#394] fix CSS for 'What's new' page

---

code/wp-content/themes/Akvo-responsive/css/main.css
code/wp-content/themes/Akvo-responsive/css/main.scss
code/wp-content/themes/Akvo-responsive/productpage-rsr-whatsnew.php

improve display on small viewports for "what's new" page per #394

[#394] improve responsive CSS for 'What's new' page

---

code/wp-content/themes/Akvo-responsive/css/main.css
code/wp-content/themes/Akvo-responsive/css/main.scss
code/wp-content/themes/Akvo-responsive/productpage-akvopedia.php

[#517] Revise Akvopedia product page to 5 portals

---

code/wp-content/themes/Akvo-responsive/css/main.css
code/wp-content/themes/Akvo-responsive/css/main.scss

[#559] improve readability of product roadmaps page text

---

code/wp-content/themes/Akvo-responsive/annual-report-2014.php
code/wp-content/themes/Akvo-responsive/css/main.css
code/wp-content/themes/Akvo-responsive/css/main.scss

#581 improvements after feedback from comms team

[#581] annual report design improvements

---

code/wp-content/themes/Akvo-responsive/css/main.css
code/wp-content/themes/Akvo-responsive/css/main.scss

[#581] annual report

---

code/wp-content/themes/Akvo-responsive/annual-report-2014.php
code/wp-content/themes/Akvo-responsive/css/main.css
code/wp-content/themes/Akvo-responsive/css/main.scss

[#581] replace gif with gfycat

---

code/wp-content/themes/Akvo-responsive/annual-report-2014.php
code/wp-content/themes/Akvo-responsive/css/main.css
code/wp-content/themes/Akvo-responsive/css/main.scss

Annual report fixes

---

code/wp-content/themes/Akvo-responsive/annual-report-2014.php
code/wp-content/themes/Akvo-responsive/css/main.css
code/wp-content/themes/Akvo-responsive/css/main.scss

Remove gfycat and use regular gif

---

code/wp-content/themes/Akvo-responsive/annual-report-2014.php
code/wp-content/themes/Akvo-responsive/css/main.css
code/wp-content/themes/Akvo-responsive/css/main.scss

Set carousel max width to 75% of viewport

---

code/wp-content/themes/Akvo-responsive/annual-report-2014.php
code/wp-content/themes/Akvo-responsive/css/main.css
code/wp-content/themes/Akvo-responsive/css/main.scss

Annual report enhancements

---

code/wp-content/themes/Akvo-responsive/annual-report-2014.php

[581] improve vimeo block check

---

code/wp-content/themes/Akvo-responsive/homepage.php

[#638] rearrange product sections

---

code/wp-content/themes/Akvo-responsive/css/main.css
code/wp-content/themes/Akvo-responsive/css/main.scss
code/wp-content/themes/Akvo-responsive/productpage-flow.php
code/wp-content/themes/Akvo-responsive/productpage-rsr.php

[#635] Add product video slot to RSR and Flow product pages

---

code/wp-content/themes/Akvo-responsive/css/main.css
code/wp-content/themes/Akvo-responsive/css/main.scss

A few additional fixes for #558

[#558] fix css in foundation page update

---

code/wp-content/themes/Akvo-responsive/homepage.php

[#638] akvo iati fixes

---

code/wp-content/themes/Akvo-responsive/css/main.css
code/wp-content/themes/Akvo-responsive/css/main.scss
code/wp-content/themes/Akvo-responsive/productpage-akvopedia.php

[#569] add sixth akvopedia portal

---

code/wp-content/themes/Akvo-responsive/css/main.css
code/wp-content/themes/Akvo-responsive/css/main.scss
code/wp-content/themes/Akvo-responsive/productpage-akvopedia.php

[#569] akvopedia portal 6 fixes

---

code/wp-content/themes/Akvo-responsive/css/main.css
code/wp-content/themes/Akvo-responsive/css/main.scss
code/wp-content/themes/Akvo-responsive/nutshell.php

[#673] Nutshell page design improvements

---

code/wp-content/themes/Akvo-responsive/header.php

[#692] Fix partner page

---

code/wp-content/themes/Akvo-responsive/css/main.css
code/wp-content/themes/Akvo-responsive/css/main.scss
code/wp-content/themes/Akvo-responsive/homepage-2015.php
code/wp-content/themes/Akvo-responsive/productPage-2015.php

[#705] layout tweaks

---

code/wp-content/themes/Akvo-responsive/css/main.css
code/wp-content/themes/Akvo-responsive/css/main.scss
code/wp-content/themes/Akvo-responsive/homepage-2015.php

#746 
Hide the video (or don't load it at all) on narrow viewports.

[#746] make video slider responsive

---

code/wp-content/themes/Akvo-responsive/homepage-2015.php

[#746] put mp4 video src before ogv

---

code/wp-content/themes/Akvo-responsive/css/main.css
code/wp-content/themes/Akvo-responsive/css/main.scss
code/wp-content/themes/Akvo-responsive/homepage-2015.php

[#746] only show video on canplay event

---

code/wp-content/themes/Akvo-responsive/css/main.css
code/wp-content/themes/Akvo-responsive/css/main.scss

[#746] resize video cover

---

code/wp-content/themes/Akvo-responsive/css/main.css
code/wp-content/themes/Akvo-responsive/css/main.scss

[#746] carousel video

---

code/wp-content/themes/Akvo-responsive/css/main.css
code/wp-content/themes/Akvo-responsive/css/main.scss

[#746] increase z index on hero captions
